### ISSUE TITLE
Can't ignore .min.js files

### ISSUE THREAD

**Issue by s-taylor** [ggreer/the_silver_searcher#710]
This command does not appear to work
ag "search" ./ --ignore=*.min.js

And yet the ignore does work with
ag "search" ./ --ignore=*.js

I can't find a solution to this issue as the regex searching is only for inclusions and not exclusions

**Comment by decaff** [comment]
When is the last time you pulled sources from master and rebuilt ag?

This very issue was addressed in PR #680 .

**Comment by s-taylor** [comment]
Thanks for your response but it doesn't seem to have fixed the issue.
I updated from 0.28 to 0.30 but the issue still remains.
If I add --ignore=*.min.js minified js files are still included
If I add --ignore=*min.js the js files are excluded

So it seems that it is treating the "." as a special character. I tried escapting this with \ but it still doesn't work.

**Comment by decaff** [comment]
````
$ ls
dad.min.js  mom.js  mom.min.js  sludge.js
$ egrep -n stuff *.js
dad.min.js:1:stuff
mom.js:1:stuff
mom.min.js:1:stuff
sludge.js:1:stuff
$ ag --ignore '.min.js' -l stuff
dad.min.js
mom.js
mom.min.js
sludge.js
$ ag --ignore '*.min.js' -l stuff
mom.js
sludge.js
$
````
The ````*```` char is needed to give fnmatch() a chance to match file wildcard patterns.

**Comment by s-taylor** [comment]
I understand the * is needed, but when I try exactly what you've listed above I do not get the same result

```
$ ls
test.js  test.min.js
$ egrep -n stuff *.js
test.js:1:stuff
test.min.js:1:stuff
$ ag --ignore '.min.js' -l stuff
test.js
test.min.js
$ ag --ignore '*.min.js' -l stuff
test.js
test.min.js
$ brew upgrade the_silver_searcher
Error: the_silver_searcher 0.30.0 already installed
```

**Comment by decaff** [comment]
The last ag version bump apparently occurred on [April 28](https://github.com/ggreer/the_silver_searcher/commit/c81622c5c5313c05eab2da3b5eca6c118b74369e).  So the ag version number is not an indicator of recent changes, like this one [17 days ago](https://github.com/ggreer/the_silver_searcher/commit/a119171e2a43eaff8983e4d462d8ea35588a80ad) .

Can you pull sources from master and manually build ag?

**Comment by s-taylor** [comment]
Let me give that a try and I'll let you know how it goes.

**Comment by joliss** [comment]
I can confirm that this is fixed in ag master (0.31.0). And being able to ignore `.min.js` files is supremely useful indeed. :)

**Comment by s-taylor** [comment]
Thanks, this works for me now, feel free to close!

**Comment by ggreer** [comment]
Good to hear. Thanks for your help and your patience.
